baseurl = "https://resch.pw/"
title = "Niklas Resch"
theme = "resch.pw-theme"
languageCode = "en-us"

# Parameters
[params]
    subtitle = ""
    dateFmt = "2006-01-02 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/thatshumbug"
        weight = 1 

    [[menu.footer]]
        name = "Mastodon"
        url = "https://chaos.social/@humbug"
        weight = 2 

    [[menu.footer]]
        name = "Imprint"
        url = "/imprint"
        weight = 3 